hashi_vault - enable use of tokens without lookup-self
ansible-collections/community.hashi_vault pull request #24
Opened 2020-12-09 03:19 UTC by briantist

##### SUMMARY
Fixes #18 

The issue has most of the technical information.

The method we use to determine if a token is valid relies on the token having the ability to lookup itself. By default, all tokens inherit the "default" policy in Vault, and by default the default policy contains that capability.

However when you create a token you may request that it doesn't include the default policy. You may also modify an installation's default policy to remove this capability.

In these cases, it would be impossible to use that (perfectly valid) token with this plugin, because it would fail early attempts to validate it.

This PR adds a new option allowing you to optionally disable that early validation.

When disabled, the token will be used to query a secret without any other checks. This means that if your token is expired or otherwise invalid, you will see the same error message as if your token wasn't granted the right permission.

- Adds a new boolean option `token_validate` to control whether a token should be validated
- Adds tests to ensure that a no-default-policy token fails with validation on and works with validation off
- Updated docs and examples

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

hashi_vault.py

##### ADDITIONAL INFORMATION

2020-12-09 03:38 UTC, briantist commented
@rasta-rocket could you try out this change?

2020-12-17 09:30 UTC, rasta-rocket requested changes
Just a little change
Great job 👍 💪👍 💪👍 💪👍 💪

2020-12-17 09:30 UTC, rasta-rocket commented on plugins/lookup/hashi_vault.py
> +- name: authenticate with aws_iam_login
```suggestion
- name: authenticate without token validation
```

2020-12-17 15:48 UTC, briantist commented
Thanks @rasta-rocket good catch! 
Were you able to try out the code itself?

2020-12-21 16:27 UTC, briantist commented
Hey @rasta-rocket looking to get this merged and released, if you have a moment do you mind reviewing once more?

2020-12-23 20:17 UTC, felixfontein reviewed
Rest looks fine (didn't look at tests).

2020-12-23 20:17 UTC, felixfontein commented on plugins/lookup/hashi_vault.py
> +      default: True
```suggestion
      default: true
      version_added: 0.2.0
```

2020-12-23 20:49 UTC, felixfontein approved these changes

2020-12-23 21:17 UTC, merged